name: CI & CD
on:
    push:
        branches:
            - dev20220209
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install & build
              run: npm run build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./.nuxt
                  # cname: ideapp.dev
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true